// Dummy Data Store
export const dummyStore = {
  users: [
    {
      id: 1,
      email: "buyer@test.com",
      username: "Buyer 1",
      telephone: "081234567890",
      address: "Jl. Test No. 123",
      role: "buyer",
      profile_picture: null,
    },
    {
      id: 2,
      email: "seller@test.com",
      username: "Seller 1",
      telephone: "081234567890",
      address: "Jl. Test No. 123",
      role: "seller",
      profile_picture: null,
    },
    {
      id: 7,
      email: "buyer2@test.com",
      username: "Buyer 2",
      telephone: "081234567890",
      address: "Jl. Test No. 123",
      role: "buyer",
      profile_picture: null,
    },
  ],
  products: [
    {
      id: 1,
      shop_id: 4,
      name: "Blue & Black Check Shirt",
      category: "Fashion",
      label: "mens-shirts",
      description:
        "The Blue & Black Check Shirt is a stylish and comfortable men's shirt featuring a classic check pattern. Made from high-quality fabric, it's suitable for both casual and semi-formal occasions.",
      image:
        "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/thumbnail.webp",
      price: 450000,
      stock: 38,
    },
    {
      id: 2,
      shop_id: 1,
      name: "Gigabyte Aorus Men Tshirt",
      category: "Fashion",
      label: "mens-shirts",
      description:
        "The Gigabyte Aorus Men Tshirt is a cool and casual shirt for gaming enthusiasts. With the Aorus logo and sleek design, it's perfect for expressing your gaming style.",
      image:
        "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/thumbnail.webp",
      price: 375000,
      stock: 90,
    },
    {
      id: 3,
      shop_id: 4,
      name: "Man Plaid Shirt",
      category: "Fashion",
      label: "mens-shirts",
      description:
        "The Man Plaid Shirt is a timeless and versatile men's shirt with a classic plaid pattern. Its comfortable fit and casual style make it a wardrobe essential for various occasions.",
      image:
        "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/thumbnail.webp",
      price: 525000,
      stock: 82,
    },
    {
      id: 4,
      shop_id: 1,
      name: "Man Short Sleeve Shirt",
      category: "Fashion",
      label: "mens-shirts",
      description:
        "The Man Short Sleeve Shirt is a breezy and stylish option for warm days. With a comfortable fit and short sleeves, it's perfect for a laid-back yet polished look.",
      image:
        "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp",
      price: 300000,
      stock: 2,
    },
    {
      id: 5,
      shop_id: 1,
      name: "Men Check Shirt",
      category: "Fashion",
      label: "mens-shirts",
      description:
        "The Men Check Shirt is a classic and versatile shirt featuring a stylish check pattern. Suitable for various occasions, it adds a smart and polished touch to your wardrobe.",
      image:
        "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/thumbnail.webp",
      price: 420000,
      stock: 95,
    },
    {
      id: 6,
      shop_id: 4,
      name: "Nike Air Jordan 1 Red And Black",
      category: "Fashion",
      label: "mens-shoes",
      description:
        "The Nike Air Jordan 1 in Red and Black is an iconic basketball sneaker known for its stylish design and high-performance features, making it a favorite among sneaker enthusiasts and athletes.",
      image:
        "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/thumbnail.webp",
      price: 2250000,
      stock: 7,
    },
    {
      id: 7,
      shop_id: 4,
      name: "Nike Baseball Cleats",
      category: "Fashion",
      label: "mens-shoes",
      description:
        "Nike Baseball Cleats are designed for maximum traction and performance on the baseball field. They provide stability and support for players during games and practices.",
      image:
        "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/thumbnail.webp",
      price: 1200000,
      stock: 12,
    },
    {
      id: 8,
      shop_id: 2,
      name: "Puma Future Rider Trainers",
      category: "Fashion",
      label: "mens-shoes",
      description:
        "The Puma Future Rider Trainers offer a blend of retro style and modern comfort. Perfect for casual wear, these trainers provide a fashionable and comfortable option for everyday use.",
      image:
        "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp",
      price: 1350000,
      stock: 90,
    },
    {
      id: 9,
      shop_id: 4,
      name: "Sports Sneakers Off White & Red",
      category: "Fashion",
      label: "mens-shoes",
      description:
        "The Sports Sneakers in Off White and Red combine style and functionality, making them a fashionable choice for sports enthusiasts. The red and off-white color combination adds a bold and energetic touch.",
      image:
        "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp",
      price: 1800000,
      stock: 17,
    },
    {
      id: 10,
      shop_id: 4,
      name: "Sports Sneakers Off White Red",
      category: "Fashion",
      label: "mens-shoes",
      description:
        "Another variant of the Sports Sneakers in Off White Red, featuring a unique design. These sneakers offer style and comfort for casual occasions.",
      image:
        "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp",
      price: 1650000,
      stock: 62,
    },
    {
      id: 11,
      shop_id: 4,
      name: "iPhone 5s",
      category: "Others",
      label: "smartphones",
      description:
        "The iPhone 5s is a classic smartphone known for its compact design and advanced features during its release. While it's an older model, it still provides a reliable user experience.",
      image:
        "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/thumbnail.webp",
      price: 3000000,
      stock: 25,
    },
    {
      id: 16,
      shop_id: 4,
      name: "Annibale Colombo Bed",
      category: "Others",
      label: "furniture",
      description:
        "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.",
      image:
        "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp",
      price: 28500000,
      stock: 88,
    },
    {
      id: 12,
      shop_id: 4,
      name: "iPhone 6",
      category: "Others",
      label: "smartphones",
      description:
        "The iPhone 6 is a stylish and capable smartphone with a larger display and improved performance. It introduced new features and design elements, making it a popular choice in its time.",
      image:
        "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp",
      price: 4500000,
      stock: 60,
    },
    {
      id: 17,
      shop_id: 1,
      name: "Annibale Colombo Sofa",
      category: "Others",
      label: "furniture",
      description:
        "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.",
      image:
        "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp",
      price: 37500000,
      stock: 60,
    },
    {
      id: 13,
      shop_id: 1,
      name: "iPhone 13 Pro",
      category: "Others",
      label: "smartphones",
      description:
        "The iPhone 13 Pro is a cutting-edge smartphone with a powerful camera system, high-performance chip, and stunning display. It offers advanced features for users who demand top-notch technology.",
      image:
        "https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp",
      price: 16500000,
      stock: 56,
    },
    {
      id: 18,
      shop_id: 4,
      name: "Bedside Table African Cherry",
      category: "Others",
      label: "furniture",
      description:
        "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.",
      image:
        "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp",
      price: 4500000,
      stock: 64,
    },
    {
      id: 14,
      shop_id: 1,
      name: "iPhone X",
      category: "Others",
      label: "smartphones",
      description:
        "The iPhone X is a flagship smartphone featuring a bezel-less OLED display, facial recognition technology (Face ID), and impressive performance. It represents a milestone in iPhone design and innovation.",
      image:
        "https://cdn.dummyjson.com/product-images/smartphones/iphone-x/thumbnail.webp",
      price: 13500000,
      stock: 37,
    },
    {
      id: 19,
      shop_id: 1,
      name: "Knoll Saarinen Executive Conference Chair",
      category: "Others",
      label: "furniture",
      description:
        "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.",
      image:
        "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp",
      price: 7500000,
      stock: 26,
    },
    {
      id: 15,
      shop_id: 4,
      name: "Oppo A57",
      category: "Others",
      label: "smartphones",
      description:
        "The Oppo A57 is a mid-range smartphone known for its sleek design and capable features. It offers a balance of performance and affordability, making it a popular choice.",
      image:
        "https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/thumbnail.webp",
      price: 3750000,
      stock: 19,
    },
    {
      id: 20,
      shop_id: 4,
      name: "Wooden Bathroom Sink With Mirror",
      category: "Others",
      label: "furniture",
      description:
        "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.",
      image:
        "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/thumbnail.webp",
      price: 12000000,
      stock: 7,
    },
  ],
  shops: [
    {
      id: 1,
      user_id: 2,
      shop_name: "Thrift Store 1",
      shop_telephone: "081234567891",
      shop_address: "Jl. Shop No. 1",
      account_number: "1234567890",
      qris_picture:
        "https://png.pngtree.com/png-vector/20191027/ourmid/pngtree-qr-code-vector-hidden-text-or-url-scanning-smartphone-technology-isolated-png-image_1886134.jpg",
      created_at: new Date().toISOString(),
      status_admin: "accept",
    },
    {
      id: 2,
      user_id: 2,
      shop_name: "Thrift Store 2",
      shop_telephone: "081234567892",
      shop_address: "Jl. Shop No. 2",
      account_number: "0987654321",
      qris_picture:
        "https://png.pngtree.com/png-vector/20191027/ourmid/pngtree-qr-code-vector-hidden-text-or-url-scanning-smartphone-technology-isolated-png-image_1886134.jpg",
      created_at: new Date().toISOString(),
      status_admin: "accept",
    },
    {
      id: 4,
      user_id: 4,
      shop_name: "Thrift Store 3",
      shop_telephone: "081234567893",
      shop_address: "Jl. Shop No. 3",
      account_number: "9876543210",
      qris_picture:
        "https://png.pngtree.com/png-vector/20191027/ourmid/pngtree-qr-code-vector-hidden-text-or-url-scanning-smartphone-technology-isolated-png-image_1886134.jpg",
      created_at: new Date().toISOString(),
      status_admin: "accept",
    },
    {
      id: 5,
      user_id: 4,
      shop_name: "Thrift Store 4",
      shop_telephone: "081234567894",
      shop_address: "Jl. Shop No. 4",
      account_number: "8765432109",
      qris_picture:
        "https://png.pngtree.com/png-vector/20191027/ourmid/pngtree-qr-code-vector-hidden-text-or-url-scanning-smartphone-technology-isolated-png-image_1886134.jpg",
      created_at: new Date().toISOString(),
      status_admin: "pending",
    },
    {
      id: 6,
      user_id: 4,
      shop_name: "Thrift Store 5",
      shop_telephone: "081234567895",
      shop_address: "Jl. Shop No. 5",
      account_number: "7654321098",
      qris_picture:
        "https://png.pngtree.com/png-vector/20191027/ourmid/pngtree-qr-code-vector-hidden-text-or-url-scanning-smartphone-technology-isolated-png-image_1886134.jpg",
      created_at: new Date().toISOString(),
      status_admin: "pending",
    },
  ],
  cart: [],
  orders: [
    {
      id: 1,
      user_id: 4,
      shop_id: 1,
      recipient: "Steven Smith",
      telephone: "081234567890",
      address: "Jl. Contoh, Jakarta, Indonesia",
      note: "Hati-hati di jalan",
      total_price: 675000,
      proof_payment: null,
      cancelBy: null,
      status_shipping: "delivered",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 2,
      user_id: 4,
      shop_id: 2,
      recipient: "Buddy Budiman",
      telephone: "08234567890",
      address: "Jl. Contoh, Bandung, Indonesia",
      note: "Awas di jalan",
      total_price: 12000000,
      proof_payment: null,
      cancelBy: null,
      status_shipping: "cancelled",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 3,
      user_id: 3,
      shop_id: 4,
      recipient: "Ello Rabyndra",
      telephone: "08239667890",
      address: "Jl. Contoh, Palembang, Indonesia",
      note: "Mohon hati-hati di jalan",
      total_price: 4500000,
      proof_payment: null,
      cancelBy: "seller",
      status_shipping: "cancelPending",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 4,
      user_id: 3,
      shop_id: 4,
      recipient: "Ello Rabyndra",
      telephone: "08239667890",
      address: "Jl. Contoh, Palembang, Indonesia",
      note: "Mohon hati-hati di jalan",
      total_price: 4500000,
      proof_payment: null,
      cancelBy: null,
      status_shipping: "prepared",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 5,
      user_id: 3,
      shop_id: 4,
      recipient: "Ello Rabyndra",
      telephone: "08239667890",
      address: "Jl. Contoh, Palembang, Indonesia",
      note: "Mohon hati-hati di jalan",
      total_price: 3000000,
      proof_payment: null,
      cancelBy: "buyer",
      status_shipping: "cancelled",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 6,
      user_id: 3,
      shop_id: 4,
      recipient: "Ello Rabyndra",
      telephone: "08239667890",
      address: "Jl. Contoh, Palembang, Indonesia",
      note: "Mohon hati-hati di jalan",
      total_price: 2400000,
      proof_payment: null,
      cancelBy: "buyer",
      status_shipping: "cancelPending",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 7,
      user_id: 3,
      shop_id: 4,
      recipient: "Ello Rabyndra",
      telephone: "08239667890",
      address: "Jl. Contoh, Palembang, Indonesia",
      note: "Mohon hati-hati di jalan",
      total_price: 1200000,
      proof_payment: null,
      cancelBy: null,
      status_shipping: "awaitingPayment",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 8,
      user_id: 4,
      shop_id: 2,
      recipient: "Steven Smith",
      telephone: "08239667890",
      address: "Jl. Contoh, Surabaya, Indonesia",
      note: "Mohon hati-hati di jalan",
      total_price: 1350000,
      proof_payment: null,
      cancelBy: "seller",
      status_shipping: "cancelPending",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 9,
      user_id: 4,
      shop_id: 2,
      recipient: "Steven Smith",
      telephone: "08239667890",
      address: "Jl. Contoh, Surabaya, Indonesia",
      note: "Mohon hati-hati di jalan",
      total_price: 4050000,
      proof_payment: null,
      cancelBy: null,
      status_shipping: "prepared",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  orderItems: [
    {
      id: 1,
      order_id: 1,
      product_id: 2,
      quantity: 1,
      price: 375000,
    },
    {
      id: 2,
      order_id: 1,
      product_id: 4,
      quantity: 1,
      price: 300000,
    },
    {
      id: 3,
      order_id: 2,
      product_id: 20,
      quantity: 1,
      price: 12000000,
    },
    {
      id: 3,
      order_id: 3,
      product_id: 18,
      quantity: 1,
      price: 4500000,
    },
    {
      id: 4,
      order_id: 4,
      product_id: 12,
      quantity: 1,
      price: 4500000,
    },
    {
      id: 5,
      order_id: 5,
      product_id: 11,
      quantity: 1,
      price: 3000000,
    },
    {
      id: 6,
      order_id: 6,
      product_id: 7,
      quantity: 2,
      price: 1200000,
    },
    {
      id: 7,
      order_id: 7,
      product_id: 7,
      quantity: 1,
      price: 1200000,
    },
    {
      id: 8,
      order_id: 8,
      product_id: 8,
      quantity: 1,
      price: 1350000,
    },
    {
      id: 9,
      order_id: 9,
      product_id: 8,
      quantity: 3,
      price: 1350000,
    },
  ],
};
