const shops = [
  {
    id: 1,
    user_id: 1,
    userName: "John Doe",
    shop_name: "Premium Fashion Store",
    shop_address: "Jl. Contoh, Jakarta, Indonesia",
    shop_telephone: "+62 812 3456 7890",
  },
];

const sampleOrders = [
  {
    id: 1,
    recipient: "John Doe",
    telephone: "+62 812 3456 7890",
    address: "Jl. Contoh, Jakarta, Indonesia",
    note: "Hati-hati di jalan",
    shop_name: "Premium Fashion Store",
    shop_id: 1,
    shop_telephone: "+62 812 3456 7890",
    orderDate: "2024-02-08T11:00:00",
    totalItems: 3,
    total_price: 75,
    status_shipping: "cancelPending",
    cancelBy: "seller",
  },
  {
    id: 2,
    recipient: "Max Mustermann",
    telephone: "+62 812 3456 7890",
    address: "Jl. Contoh, Jakarta, Indonesia",
    note: "Hati-hati di jalan",
    shop_name: "Good Fashion Store",
    shop_id: 2,
    shop_telephone: "+62 856 7890 1234",
    orderDate: "2024-02-07T14:30:00",
    totalItems: 1,
    total_price: 300,
    status_shipping: "prepared",
    cancelBy: "",
  },
  {
    id: 3,
    recipient: "John Doe",
    telephone: "+62 812 3456 7890",
    address: "Jl. Contoh, Jakarta, Indonesia",
    note: "Hati-hati di jalan",
    shop_name: "Home & Living",
    shop_id: 3,
    shop_telephone: "+62 821 9876 5432",
    orderDate: "2024-02-06T09:15:00",
    totalItems: 5,
    total_price: 183.33,
    status_shipping: "awaitingPayment",
    cancelBy: "",
  },
  {
    id: 4,
    recipient: "John Doe",
    telephone: "+62 812 3456 7890",
    address: "Jl. Contoh, Jakarta, Indonesia",
    note: "Hati-hati di jalan",
    shop_name: "Beauty & Care",
    shop_id: 4,
    shop_telephone: "+62 878 1234 5678",
    orderDate: "2024-02-05T16:45:00",
    totalItems: 2,
    total_price: 56.67,
    status_shipping: "cancelled",
    cancelBy: "seller",
  },
  {
    id: 5,
    recipient: "John Doe",
    telephone: "+62 812 3456 7890",
    address: "Jl. Contoh, Jakarta, Indonesia",
    note: "Hati-hati di jalan",
    shop_name: "Gaming Store",
    shop_id: 5,
    shop_telephone: "+62 848 1224 5678",
    orderDate: "2024-02-05T16:45:00",
    totalItems: 2,
    total_price: 16.67,
    status_shipping: "cancelPending",
    cancelBy: "buyer",
  },
  {
    id: 6,
    recipient: "John Doe",
    telephone: "+62 812 3456 7890",
    address: "Jl. Contoh, Jakarta, Indonesia",
    note: "Hati-hati di jalan",
    shop_name: "Food & Groceries",
    shop_id: 6,
    shop_telephone: "+62 848 1224 5728",
    orderDate: "2024-02-05T16:45:00",
    totalItems: 2,
    total_price: 10.67,
    status_shipping: "delivered",
    cancelBy: "",
  },
];

const orderItems = [
  {
    id: 1,
    order_id: 1,
    name: "Blue & Black Check Shirt",
    label: "mens shirts",
    quantity: 2,
    price: 10,
    image:
      "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/thumbnail.webp",
  },
  {
    id: 2,
    order_id: 1,
    name: "Nike Air Jordan 1 Red And Black",
    label: "mens shoes",
    quantity: 1,
    price: 15,
    image:
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/thumbnail.webp",
  },
  {
    id: 3,
    order_id: 2,
    name: "Sports Sneakers Off White & Red",
    label: "mens shoes",
    quantity: 3,
    price: 12,
    image:
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp",
  },
  {
    id: 4,
    order_id: 3,
    name: "Sports Sneakers Off White & Red",
    label: "mens shoes",
    quantity: 3,
    price: 12,
    image:
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp",
  },
  {
    id: 5,
    order_id: 4,
    name: "Sports Sneakers Off White & Red",
    label: "mens shoes",
    quantity: 3,
    price: 12,
    image:
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp",
  },
  {
    id: 6,
    order_id: 5,
    name: "Sports Sneakers Off White & Red",
    label: "mens shoes",
    quantity: 3,
    price: 12,
    image:
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp",
  },
  {
    id: 7,
    order_id: 6,
    name: "Sports Sneakers Off White & Red",
    label: "mens shoes",
    quantity: 3,
    price: 12,
    image:
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp",
  },
];

const allUsers = [
  {
    id: 1,
    username: "Darlene Robertson",
    email: "alma.lawson@example.com",
    telephone: "(252) 555-0126",
    address: "123 Main St, New York, NY 10001",
    role: "Buyer",
  },
  {
    id: 2,
    username: "Annette Black",
    email: "bill.sanders@example.com",
    telephone: "(252) 555-0126",
    address: "456 Oak Ave, Los Angeles, CA 90001",
    role: "Seller",
  },
  {
    id: 3,
    username: "Ronald Richards",
    email: "weaver@example.com",
    telephone: "(252) 555-0126",
    address: "789 Pine Rd, Chicago, IL 60601",
    role: "Buyer",
  },
  {
    id: 4,
    username: "Ralph Edwards",
    email: "simmons@example.com",
    telephone: "(252) 555-0126",
    address: "321 Elm St, Houston, TX 77001",
    role: "Seller",
  },
  {
    id: 5,
    username: "Jenny Wilson",
    email: "jenny.wilson@example.com",
    telephone: "(252) 555-0126",
    address: "654 Maple Dr, Phoenix, AZ 85001",
    role: "Buyer",
  },
];

const allShops = [
  {
    id: 1,
    user_id: 1,
    email: "johndoe@gmail.com",
    shop_name: "Premium Fashion Store",
    shop_address: "Jl. Contoh No. 10, Jakarta, Indonesia",
    shop_telephone: "+62 812 3456 7890",
    status_admin: "Accept",
  },
  {
    id: 2,
    user_id: 2,
    email: "mariasantoso@gmail.com",
    shop_name: "TechZone Electronics",
    shop_address: "Jl. Merdeka No. 25, Bandung, Indonesia",
    shop_telephone: "+62 813 2233 4455",
    status_admin: "Accept",
  },
  {
    id: 3,
    user_id: 3,
    email: "rafihidayat@gmail.com",
    shop_name: "Rafi’s Coffee Corner",
    shop_address: "Jl. Kopi No. 88, Surabaya, Indonesia",
    shop_telephone: "+62 819 5566 7788",
    status_admin: "Accept",
  },
  {
    id: 4,
    user_id: 4,
    email: "sintalestari@gmail.com",
    shop_name: "Sinta Beauty & Care",
    shop_address: "Jl. Mawar No. 5, Yogyakarta, Indonesia",
    shop_telephone: "+62 812 9988 7766",
    status_admin: "Accept",
  },
  {
    id: 5,
    user_id: 5,
    email: "andipratama@gmail.com",
    shop_name: "Andi’s Gadget Hub",
    shop_address: "Jl. Melati No. 12, Medan, Indonesia",
    shop_telephone: "+62 815 3344 5566",
    status_admin: "Accept",
  },
  {
    id: 6,
    user_id: 6,
    email: "dewianggraini@gmail.com",
    shop_name: "Dewi Handmade Crafts",
    shop_address: "Jl. Kenanga No. 14, Semarang, Indonesia",
    shop_telephone: "+62 817 4455 6677",
    status_admin: "Pending",
  },
  {
    id: 7,
    user_id: 7,
    email: "budisetiawan@gmail.com",
    shop_name: "Budi Auto Parts",
    shop_address: "Jl. Veteran No. 7, Makassar, Indonesia",
    shop_telephone: "+62 814 7788 9900",
    status_admin: "Pending",
  },
  {
    id: 8,
    user_id: 8,
    email: "lisawijaya@gmail.com",
    shop_name: "Lisa’s Bookstore",
    shop_address: "Jl. Cendana No. 9, Denpasar, Indonesia",
    shop_telephone: "+62 811 3344 5566",
    status_admin: "Pending",
  },
  {
    id: 9,
    user_id: 9,
    email: "rizkymaulana@gmail.com",
    shop_name: "Rizky Outdoor Gear",
    shop_address: "Jl. Pelita No. 18, Palembang, Indonesia",
    shop_telephone: "+62 818 2211 3344",
    status_admin: "Pending",
  },
  {
    id: 10,
    user_id: 10,
    email: "ayupermata@gmail.com",
    shop_name: "Ayu Kids Fashion",
    shop_address: "Jl. Anggrek No. 22, Balikpapan, Indonesia",
    shop_telephone: "+62 819 6677 8899",
    status_admin: "Pending",
  },
];

export { shops, sampleOrders, orderItems, allUsers, allShops };
