const shops = [
  {
    id: 1,
    userId: 1,
    userName: "John Doe",
    shopName: "Premium Fashion Store",
    shopAddress: "Jl. Contoh, Jakarta, Indonesia",
    shopTelephone: "+62 812 3456 7890",
  },
];

const sampleOrders = [
  {
    id: 1,
    recepient: "John Doe",
    telephone: "+62 812 3456 7890",
    address: "Jl. Contoh, Jakarta, Indonesia",
    note: "Hati-hati di jalan",
    shopName: "Premium Fashion Store",
    shopId: 1,
    shopPhone: "+62 812 3456 7890",
    orderDate: "2024-02-08T11:00:00",
    totalItems: 3,
    totalPrice: 75,
    statusShipping: "cancelPending",
    cancelBy: "seller",
  },
  {
    id: 2,
    recepient: "Max Mustermann",
    telephone: "+62 812 3456 7890",
    address: "Jl. Contoh, Jakarta, Indonesia",
    note: "Hati-hati di jalan",
    shopName: "Good Fashion Store",
    shopId: 2,
    shopPhone: "+62 856 7890 1234",
    orderDate: "2024-02-07T14:30:00",
    totalItems: 1,
    totalPrice: 300,
    statusShipping: "prepared",
    cancelBy: "",
  },
  {
    id: 3,
    recepient: "John Doe",
    telephone: "+62 812 3456 7890",
    address: "Jl. Contoh, Jakarta, Indonesia",
    note: "Hati-hati di jalan",
    shopName: "Home & Living",
    shopId: 3,
    shopPhone: "+62 821 9876 5432",
    orderDate: "2024-02-06T09:15:00",
    totalItems: 5,
    totalPrice: 183.33,
    statusShipping: "awaitingPayment",
    cancelBy: "",
  },
  {
    id: 4,
    recepient: "John Doe",
    telephone: "+62 812 3456 7890",
    address: "Jl. Contoh, Jakarta, Indonesia",
    note: "Hati-hati di jalan",
    shopName: "Beauty & Care",
    shopId: 4,
    shopPhone: "+62 878 1234 5678",
    orderDate: "2024-02-05T16:45:00",
    totalItems: 2,
    totalPrice: 56.67,
    statusShipping: "cancelled",
    cancelBy: "seller",
  },
  {
    id: 5,
    recepient: "John Doe",
    telephone: "+62 812 3456 7890",
    address: "Jl. Contoh, Jakarta, Indonesia",
    note: "Hati-hati di jalan",
    shopName: "Gaming Store",
    shopId: 5,
    shopPhone: "+62 848 1224 5678",
    orderDate: "2024-02-05T16:45:00",
    totalItems: 2,
    totalPrice: 16.67,
    statusShipping: "cancelPending",
    cancelBy: "buyer",
  },
  {
    id: 6,
    recepient: "John Doe",
    telephone: "+62 812 3456 7890",
    address: "Jl. Contoh, Jakarta, Indonesia",
    note: "Hati-hati di jalan",
    shopName: "Food & Groceries",
    shopId: 6,
    shopPhone: "+62 848 1224 5728",
    orderDate: "2024-02-05T16:45:00",
    totalItems: 2,
    totalPrice: 10.67,
    statusShipping: "delivered",
    cancelBy: "",
  },
];

const orderItems = [
  {
    id: 1,
    orderId: 1,
    name: "Blue & Black Check Shirt",
    label: "mens shirts",
    quantity: 2,
    price: 10,
    image:
      "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/thumbnail.webp",
  },
  {
    id: 2,
    orderId: 1,
    name: "Nike Air Jordan 1 Red And Black",
    label: "mens shoes",
    quantity: 1,
    price: 15,
    image:
      "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/thumbnail.webp",
  },
  {
    id: 3,
    orderId: 2,
    name: "Sports Sneakers Off White & Red",
    label: "mens shoes",
    quantity: 3,
    price: 12,
    image:
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp",
  },
  {
    id: 4,
    orderId: 3,
    name: "Sports Sneakers Off White & Red",
    label: "mens shoes",
    quantity: 3,
    price: 12,
    image:
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp",
  },
  {
    id: 5,
    orderId: 4,
    name: "Sports Sneakers Off White & Red",
    label: "mens shoes",
    quantity: 3,
    price: 12,
    image:
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp",
  },
  {
    id: 6,
    orderId: 5,
    name: "Sports Sneakers Off White & Red",
    label: "mens shoes",
    quantity: 3,
    price: 12,
    image:
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp",
  },
  {
    id: 7,
    orderId: 6,
    name: "Sports Sneakers Off White & Red",
    label: "mens shoes",
    quantity: 3,
    price: 12,
    image:
      "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp",
  },
];

const allUsers = [
  {
    id: 1,
    username: "Darlene Robertson",
    email: "alma.lawson@example.com",
    telephone: "(252) 555-0126",
    address: "123 Main St, New York, NY 10001",
    role: "Buyer",
  },
  {
    id: 2,
    username: "Annette Black",
    email: "bill.sanders@example.com",
    telephone: "(252) 555-0126",
    address: "456 Oak Ave, Los Angeles, CA 90001",
    role: "Seller",
  },
  {
    id: 3,
    username: "Ronald Richards",
    email: "weaver@example.com",
    telephone: "(252) 555-0126",
    address: "789 Pine Rd, Chicago, IL 60601",
    role: "Buyer",
  },
  {
    id: 4,
    username: "Ralph Edwards",
    email: "simmons@example.com",
    telephone: "(252) 555-0126",
    address: "321 Elm St, Houston, TX 77001",
    role: "Seller",
  },
  {
    id: 5,
    username: "Jenny Wilson",
    email: "jenny.wilson@example.com",
    telephone: "(252) 555-0126",
    address: "654 Maple Dr, Phoenix, AZ 85001",
    role: "Buyer",
  },
];

export { shops, sampleOrders, orderItems, allUsers };
